const stockTradingFirms = [
  {
    'id': 0,
    'module': 'secNHqv',
    'name': 'NH투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_농협.png',
  },
  {
    'id': 1,
    'module': 'secDaishin',
    'name': '대신증권',
    'image': 'assets/firm_images/금융아이콘_PNG_대신증권.png',
  },
  {
    'id': 2,
    'module': 'secSamsung',
    'name': '삼성증권',
    'image': 'assets/firm_images/금융아이콘_PNG_삼성.png',
  },
  {
    'id': 3,
    'module': 'secMyasset',
    'name': '유안타증권',
    'image': 'assets/firm_images/금융아이콘_PNG_유안타.png',
  },
  {
    'id': 4,
    'module': 'secHanaw',
    'name': '하나금융투자',
    'image': 'assets/firm_images/금융아이콘_PNG_하나.png',
  },
  {
    'id': 5,
    'module': 'secKyobo',
    'name': '교보증권',
    'image': 'assets/firm_images/금융아이콘_PNG_교보.png',
  },
  {
    'id': 6,
    'module': 'secImeritz',
    'name': '메리츠종금증권',
    'image': 'assets/firm_images/금융아이콘_PNG_메리츠.png',
  },
  {
    'id': 7,
    'module': 'secCape',
    'name': '케이프투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_케이프.png'
  },
  {
    'id': 8,
    'module': 'secIbk',
    'name': 'IBK투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_IBK.png',
  },
  {
    'id': 9,
    'module': 'secWoori',
    'name': '우리종합금융',
    'image': 'assets/firm_images/금융아이콘_PNG_우리.png',
  },
  {
    'id': 10,
    'module': 'secHi',
    'name': '하이투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_DGB.png',
  },
  {
    'id': 11,
    'module': 'secHmc',
    'name': '현대차투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_현대차증권.png',
  },
  {
    'id': 12,
    'module': 'secNamuh',
    'name': 'NH나무증권',
    'image': 'assets/firm_images/금융아이콘_PNG_나무.png',
  },
  {
    'id': 13,
    'module': 'secFoss',
    'name': '포스증권',
    'image': 'assets/firm_images/금융아이콘_PNG_한국포스.png',
  },
  {
    'id': 14,
    'module': 'secSKs',
    'name': 'SK증권',
    'image': 'assets/firm_images/금융아이콘_PNG_SK.png',
  },
  {
    'id': 15,
    'module': 'secMirae',
    'name': '미래에셋증권',
    'image': 'assets/firm_images/금융아이콘_PNG_미래에셋.png',
  },
  {
    'id': 16,
    'module': 'secShinhan',
    'name': '신한금융투자',
    'image': 'assets/firm_images/금융아이콘_PNG_신한.png',
  },
  {
    'id': 17,
    'module': 'secKiwoom',
    'name': '키움증권',
    'image': 'assets/firm_images/금융아이콘_PNG_키움.png',
  },
  {
    'id': 18,
    'module': 'secKB',
    'name': 'KB증권',
    'image': 'assets/firm_images/금융아이콘_PNG_KB.png',
  },
  {
    'id': 19,
    'module': 'secDBfi',
    'name': 'DB금융투자',
    'image': 'assets/firm_images/금융아이콘_PNG_DB.png',
  },
  {
    'id': 20,
    'module': 'secHanwhawm',
    'name': '한화투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_한화.png',
  },
  {
    'id': 21,
    'module': 'secEugenefn',
    'name': '유진투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_유진.png',
  },
  {
    'id': 22,
    'module': 'secKtb',
    'name': 'KTB투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_KTB투자증권.png',
  },
  {
    'id': 23,
    'module': 'secEBest',
    'name': '이베스트투자',
    'image': 'assets/firm_images/금융아이콘_PNG_이베스트.png',
  },
  {
    'id': 24,
    'module': 'secKorea',
    'name': '한국투자증권',
    'image': 'assets/firm_images/금융아이콘_PNG_한국투자.png',
  },
  {
    'id': 25,
    'module': 'secShinyoung',
    'name': '신영증권',
    'image': 'assets/firm_images/금융아이콘_PNG_신영증권.png',
  },
  {
    'id': 26,
    'module': 'secCreon',
    'name': '크레온증권',
    'image': 'assets/firm_images/금융아이콘_PNG_크레온.png',
  },
];
